### ISSUE TITLE
Incrementar a interatividade do componente de exemplo.

### ISSUE THREAD

**Issue by matheusgr** [wesleysan7os/cine94#1]
Pelo que entendo, a interatividade vai acontecer muito pelo filtro e/ou tags. Talvez seja o caso de tentar pensar em alguma outra estratégia para aumentar a interatividade desses elementos. Criar, por exemplo, uma tag com hierarquia. Ao selecionar uma tag, ela pode 'expandir' subtags que poderiam ser selecionadas.

**Comment by wesleysan7os** [comment]
Faz muito sentido. Eu poderia, por exemplo, adicionar tags mães como "gênero", "década de lançamento", "idioma" etc. Obrigado! Continuarei pensando em outras formas de deixar a aplicação mais reativa.
