### ISSUE TITLE
Usar a nomeclatura index.jsx para o componente principal de um path

### ISSUE THREAD

**Issue by vitoria** [wesleysan7os/cine94#4]
Atribuindo o nome `index.jsx` como o nome do arquivo do componente principal de um diretório, quando você for importar esse componente, você não vai precisar colocar o nome do arquivo.

Exemplo:

Considerando o componente [Sidebar]() e fazendo essa alteração:

`src/components/sideBar/SideBard.jsx` -> `src/components/SideBar/index.jsx`

Poderiamos importar esse componente da seguinte forma:

```jsx
import SideBar from "../../components/SideBard";
``` 

Ao invés de:

```jsx
import SideBar from "../../components/sideBar/SideBard";
```

**Comment by wesleysan7os** [comment]
Obrigado pela sugestão. Feito \o
